<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page {
            margin: 0;
        }
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #333;
            background: #fff;
        }
        
        /* Cover Page */
        .cover-page {
            page-break-after: always;
            height: 100vh;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 60px;
            color: white;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .cover-page h1 {
            font-size: 48px;
            margin-bottom: 30px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }
        .cover-page .theme {
            font-size: 24px;
            margin-bottom: 20px;
            opacity: 0.9;
        }
        .cover-page .author {
            font-size: 18px;
            margin-top: 40px;
            opacity: 0.8;
        }
        .cover-page .date {
            font-size: 14px;
            margin-top: 10px;
            opacity: 0.7;
        }
        
        /* Content Pages */
        .content-page {
            padding: 60px;
            page-break-after: always;
        }
        .content-page h2 {
            color: #667eea;
            font-size: 32px;
            margin-bottom: 30px;
            text-align: center;
        }
        .story-content {
            font-size: 14px;
            line-height: 1.8;
            text-align: justify;
            margin-bottom: 40px;
        }
        .story-content p {
            margin-bottom: 20px;
        }
        
        /* Image Pages */
        .image-page {
            page-break-after: always;
            padding: 60px 40px;
            text-align: center;
        }
        .image-page img {
            max-width: 90%;
            height: auto;
            margin: 20px auto;
            display: block;
            border: 3px solid #667eea;
            border-radius: 10px;
        }
        .image-caption {
            margin-top: 20px;
            font-size: 11px;
            color: #555;
            font-style: italic;
            padding: 0 40px;
        }
        
        /* Footer */
        .footer {
            position: fixed;
            bottom: 30px;
            left: 60px;
            right: 60px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover-page">
        <div>
            <h1>{{ $title }}</h1>
            @if($story->theme)
                <div class="theme">{{ ucfirst($story->theme) }} • {{ ucfirst($story->style) }}</div>
            @endif
            <div class="author">Created by {{ $author }}</div>
            <div class="date">{{ $generatedDate }}</div>
        </div>
    </div>

    <!-- Images -->
    @if(count($images) > 0)
        @foreach($images as $index => $image)
            <div class="image-page">
                <h3 style="color: #667eea; font-size: 24px; margin-bottom: 30px;">Scene {{ $index + 1 }}</h3>
                <img src="{{ $image['src'] }}" alt="Scene {{ $index + 1 }}">
                @if(!empty($image['description']))
                    <div class="image-caption">{{ $image['description'] }}</div>
                @endif
            </div>
        @endforeach
    @endif

    <!-- Story Content -->
    <div class="content-page">
        <h2>The Story</h2>
        <div class="story-content">
            {!! nl2br(e($content)) !!}
        </div>
    </div>

    <!-- Footer on all pages -->
    <div class="footer">
        Generated by AI Story Generator • {{ $generatedDate }}
    </div>
</body>
</html>

